trigger:
- master
- main

pool:
  name: Default

steps:


- script: ls -la
  displayName: 'listing'

##########################connect 2 sunarqube#######################################

- task: SonarQubePrepare@7
  inputs:
    SonarQube: 'sonarcube_for_pipeline'
    scannerMode: 'dotnet'
    dotnetScannerVersion: '8.0.115'
    projectKey: 'MySampleApp'
    projectName: 'MySampleApp'


##########################restore and pack#######################################

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '*/.csproj'
    feedsToUse: 'select'
    vstsFeed: 'Yc23485ab-5043-4e9c-b5fb-74ea3921a802' #roy change this  to yours
  displayName:  restore
  
- task: DotNetCoreCLI@2
  displayName: 'build'
  inputs:
    command: 'build'
    projects: '*/.csproj'




###########################sonarqube check and publish################################


- task: SonarQubeAnalyze@7
  inputs:
    jdkversion: 'JAVA_HOME_17_X64'

- task: SonarQubePublish@7
  inputs:
    pollingTimeoutSec: '300'

##########################pack#######################################


- script: |
    BRANCH_NAME=$(echo $(Build.SourceBranch) | sed 's/refs\/heads\///')
    dotnet pack -p:Version=1.0.$(Build.BuildId) -p:PackageId=${BRANCH_NAME}_$(Build.BuildId) -o ./lola
  displayName: pack to lola

##########################debuging#######################################

- script: ls -la
  displayName: 'listing2'

- script: ls -la ./lola
  displayName: 'listing lola directory'

##########################push#######################################
- task: DotNetCoreCLI@2
  displayName: 'push'
  inputs:
    azureSubscription: 'Azure subscription 1(Yc23485ab-5043-4e9c-b5fb-74ea3921a802)'   #roy change this  to yours
    command: 'push'
    packagesToPush: './lola/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '08c3489a-38c5-40c0-bace-d3a3d3307e71'