trigger:
- master
- main

pool:
  name: Default

variables:
  feedId: 'e8a1abd1-1b1d-403c-8d3c-8917889e585f' # Update with your actual feed ID
  azureServiceConnection: 'SonarQube_Service_Connection' # Update with your actual service connection name

steps:
- script: ls -la
  displayName: 'listing'

##########################connect 2 sonarqube#######################################
- task: SonarQubePrepare@7
  inputs:
    SonarQube: 'SonarQube_Service_Connection' # Ensure this matches your service connection name
    scannerMode: 'dotnet'
    dotnetScannerVersion: '8.0.115'
    projectKey: 'MySampleApp'
    projectName: 'MySampleApp'

##########################restore and pack#######################################
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '*/.csproj'
    feedsToUse: 'select'
    vstsFeed: '$(feedId)'
  displayName: restore
  
- task: DotNetCoreCLI@2
  displayName: 'build'
  inputs:
    command: 'build'
    projects: '*/.csproj'

###########################sonarqube check and publish################################
- task: SonarQubeAnalyze@7
  inputs:
    jdkversion: 'JAVA_HOME_17_X64'

- task: SonarQubePublish@7
  inputs:
    pollingTimeoutSec: '300'

##########################pack#######################################
- script: |
    BRANCH_NAME=$(echo $(Build.SourceBranch) | sed 's/refs\/heads\///')
    dotnet pack -p:Version=1.0.$(Build.BuildId) -p:PackageId=${BRANCH_NAME}_$(Build.BuildId) -o ./lola
  displayName: pack to lola

##########################debuging#######################################
- script: ls -la
  displayName: 'listing2'

- script: ls -la ./lola
  displayName: 'listing lola directory'

##########################push#######################################
- task: DotNetCoreCLI@2
  displayName: 'push'
  inputs:
    azureSubscription: '$(azureServiceConnection)'
    command: 'push'
    packagesToPush: './lola/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '$(feedId)'